#pragma once
#ifndef CE_API_CLOAKENGINE_H
#define CE_API_CLOAKENGINE_H

#include "CloakEngine/Defines.h"
#include "CloakEngine/OS.h"

#include "CloakEngine/Global/Audio.h"
#include "CloakEngine/Global/Connection.h"
#include "CloakEngine/Global/Debug.h"
#include "CloakEngine/Global/DebugLayer.h"
#include "CloakEngine/Global/Draw.h"
#include "CloakEngine/Global/Game.h"
#include "CloakEngine/Global/GameEvents.h"
#include "CloakEngine/Global/Graphic.h"
#include "CloakEngine/Global/Input.h"
#include "CloakEngine/Global/Localization.h"
#include "CloakEngine/Global/Log.h"
#include "CloakEngine/Global/Math.h"
#include "CloakEngine/Global/Memory.h"
#include "CloakEngine/Global/Mouse.h"
#include "CloakEngine/Global/Steam.h"
#include "CloakEngine/Global/Task.h"
#include "CloakEngine/Global/Video.h"

#include "CloakEngine/Launcher/Launcher.h"

#include "CloakEngine/Helper/Color.h"
#include "CloakEngine/Helper/EventBase.h"
#include "CloakEngine/Helper/Logic.h"
#include "CloakEngine/Helper/Predicate.h"
#include "CloakEngine/Helper/Reflection.h"
#include "CloakEngine/Helper/SavePtr.h"
#include "CloakEngine/Helper/StateMachine.h"
#include "CloakEngine/Helper/StringConvert.h"
#include "CloakEngine/Helper/SyncSection.h"
#include "CloakEngine/Helper/Types.h"
#include "CloakEngine/Helper/UIDs.h"

#include "CloakEngine/Files/Hash/Blake2.h"
#include "CloakEngine/Files/Hash/FNV.h"
#include "CloakEngine/Files/Hash/SHA256.h"

#include "CloakEngine/Files/Animation.h"
#include "CloakEngine/Files/BoundingVolume.h"
#include "CloakEngine/Files/Buffer.h"
#include "CloakEngine/Files/ExtendedBuffers.h"
#include "CloakEngine/Files/Compressor.h"
#include "CloakEngine/Files/Configuration.h"
#include "CloakEngine/Files/FileHandler.h"
#include "CloakEngine/Files/Font.h"
#include "CloakEngine/Files/Image.h"
#include "CloakEngine/Files/Language.h"
#include "CloakEngine/Files/Mesh.h"
#include "CloakEngine/Files/Scene.h"
#include "CloakEngine/Files/Shader.h"

#include "CloakEngine/Interface/BasicGUI.h"
#include "CloakEngine/Interface/Button.h"
#include "CloakEngine/Interface/CheckButton.h"
#include "CloakEngine/Interface/DropDownMenu.h"
#include "CloakEngine/Interface/EditBox.h"
#include "CloakEngine/Interface/Frame.h"
#include "CloakEngine/Interface/Label.h"
#include "CloakEngine/Interface/ListMenu.h"
#include "CloakEngine/Interface/LoadScreen.h"
#include "CloakEngine/Interface/Menu.h"
#include "CloakEngine/Interface/MoveableFrame.h"
#include "CloakEngine/Interface/ProgressBar.h"
#include "CloakEngine/Interface/Slider.h"

#include "CloakEngine/Rendering/Allocator.h"
#include "CloakEngine/Rendering/BasicBuffer.h"
#include "CloakEngine/Rendering/ColorBuffer.h"
#include "CloakEngine/Rendering/CommandSignature.h"
#include "CloakEngine/Rendering/Context.h"
#include "CloakEngine/Rendering/DataTypes.h"
#include "CloakEngine/Rendering/Defines.h"
#include "CloakEngine/Rendering/DepthBuffer.h"
#include "CloakEngine/Rendering/Manager.h"
#include "CloakEngine/Rendering/PipelineState.h"
#include "CloakEngine/Rendering/Query.h"
#include "CloakEngine/Rendering/RenderPass.h"
#include "CloakEngine/Rendering/Resource.h"
#include "CloakEngine/Rendering/RootDescription.h"
#include "CloakEngine/Rendering/StructuredBuffer.h"

#include "CloakEngine/World/ComponentManager.h"
#include "CloakEngine/World/Entity.h"
#include "CloakEngine/World/Terrain.h"

#include "CloakEngine/Components/AudioListener.h"
#include "CloakEngine/Components/AudioSource.h"
#include "CloakEngine/Components/Camera.h"
#include "CloakEngine/Components/Light.h"
#include "CloakEngine/Components/Moveable.h"
#include "CloakEngine/Components/Position.h"
#include "CloakEngine/Components/Render.h"

#pragma comment(lib,"cloakengine.lib")

#endif
